name: Ubuntu-CI

on: 
    push:
        branches: ["main"]

jobs:
    build: 
                
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Branch main and Vcpkg repository
              uses: actions/checkout@v4.1.1
              with: 
                submodules: true
          
            - name: Install CMake and Ninja
              uses: lukka/get-cmake@latest
            
            - name: install Allegro Dependencies
              run: |
                sudo add-apt-repository ppa:allegro/5.2
                sudo apt update
                sudo apt install liballegro*5.2 liballegro*5-dev build-essential libssl-dev curl
            
            - name: Run cmake and build with cmake
              uses: lukka/run-cmake@v10.7
              with: 
                configurePreset: 'ninja-configure'
                buildPreset: 'ninja-build-release'

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: ubuntu-release
                path: |
                  build/*
                  !build/vcpkg_installed
                  !build/CMakeFiles
                  !build/.ninja_deps
                  !build/.ninja_log
                  !build/build.ninja
                  !build/CMakeCache.txt
                  !build/vcpkg-manifest-install.log
                  !build/cmake_install.cmake
                if-no-files-found: 'error'
