name: Ubuntu-CI

on: 
    push:
        branches: ["main"]

jobs:
    build: 
                
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Branch main and Vcpkg repository
              uses: actions/checkout@v4.1.1
              with: 
                submodules: true
            
            - name: Install basics
              run: |
               sudo apt update -y
               sudo apt install -y git cmake build-essential linux-libc-dev ninja-build
               sudo apt install -y libssl-dev curl
            
            - name: Install Allegro dependencies
              run: >
               sudo apt install -y libdumb1-dev libflac-dev libfreetype6-dev libgl1-mesa-dev 
               libglu1-mesa-dev libgtk-3-dev libjpeg-dev libopenal-dev libphysfs-dev libpng-dev
               libpulse-dev libtheora-dev libvorbis-dev libwebp-dev libxext-dev libxxf86vm-dev 
               libxrandr-dev libxinerama-dev libxpm-dev libopusfile-dev

            - name: Run Vcpkg for installing Allegro5
              uses: lukka/run-vcpkg@v11.5
              with:
                vcpkgJsonGlob: 'vcpkg.json'

            - name: Run cmake for build the program
              run: |
                cmake . --preset='ninja-configure'
                cmake . --build --preset='ninja-build-release' -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_C_COMPILER=/usr/bin/gcc

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with: 
                name: ubuntu-release
                path: |
                  build/*
                  !build/vcpkg_installed
                  !build/CMakeFiles
                  !build/.ninja_deps
                  !build/.ninja_log
                  !build/build.ninja
                  !build/CMakeCache.txt
                  !build/vcpkg-manifest-install.log
                  !build/cmake_install.cmake
                if-no-files-found: 'error'
