name: Windows-CI

on: 
    push:
        tags:
          - 'v*'

permissions: read-all

jobs:
    build: 
        strategy:
            matrix:
                os: [ubuntu-latest,windows-latest,macos-latest]
                
        runs-on: ${{matrix.os}}

        steps:
            - name: Checkout Branch main and Vcpkg repository
              uses: actions/checkout@v4.1.1
              with: 
                submodules: true
          
            - name: Install CMake and Ninja
              uses: lukka/get-cmake@latest
            
            - name: run-vcpkg              
              uses: lukka/run-vcpkg@v11.5
              with: 
                vcpkgJsonGlob: 'vcpkg.json'
            
            - name: Run cmake and build with cmake
              uses: lukka/run-cmake@v10.7
              with: 
                configurePreset: 'ninja-configure'
                buildPreset: 'ninja-build-release'
            
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env: 
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with: 
                tag_name: ${{github.ref}}
                release_name: Release ${{github.ref}}
                draft: false
                prerelease: true

            - name: Zip Files
              run: |
                cd build
                zip -u -r build.zip . -x .ninja_log .ninja_deps build.ninja log.txt \
                          cmake_install.cmake CMakeCache.txt compile_commands.json \
                          .cmake/* CMakeFiles/* 

            - name: Upload Release Asset
              id: upload-release-asset 
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: build/build.zip
                asset_name: ${{matrix.os}}-version-${{github.ref}}.zip
                asset_content_type: application/zip
